version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nb-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: notif_bridge_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: nb-redis
    ports:
      - "6379:6379"