services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: nb-server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://admin:password123@postgres:5432/notif_bridge_db?schema=public"
      REDIS_URL: "redis://redis:6379"
      API_KEY: "azerty"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: echo-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: notif_bridge_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: nb-redis
    ports:
      - "6379:6379"